# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.6"
    - name: Enable project resources access
      run: |
        sudo chmod -R 777 ./resources
        pwd
        whoami
        mkdir ./resources/test
    - name: Install dependencies
      run: |
        python3 -m venv venv
        ls -al
        source ./venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        source ./venv/bin/activate
        pytest --cov
